### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by Dzndrx** [Dzndrx/SEBC#1]
# CM Install Lab - Prepare your instances

**Created 5 instances m4.xlarge**
InstanceType: m4.xlarge
Storage: 30gb (EBS)
OS: Centos 7.4.1708

![cl9oudera](https://user-images.githubusercontent.com/25340342/40008486-01ab6a16-57d2-11e8-855c-3f4eae659116.png)

**Security Group**
Everything is allowed (inbound)
![security](https://user-images.githubusercontent.com/25340342/40008632-5baf2eda-57d2-11e8-915b-cd67055e9911.png)

> I didn't put any security on outbound (I guess we don't need to? Please validate @manojsundaram )

**Comment by Dzndrx** [comment]
# System Configuration Checks

**Comment by Dzndrx** [comment]
# System Configuration Checks

**We can agree for some things here in this part. (Also for validation @manojsundaram)** 
1. All my volumes on linux are XFS
2. I discover that there is some sort of NTP installed on the AWS instances (but we cannot see it thru the linux) I guess it is working before the clusters even start. Since all the date&time across the cluster are the same so I didn't install NTP as it will be redundancy for me. I can show this one on the 1_preinstall.md.
3. We also discover that the public Ip's of the AWS instances are changing every restart, so we cannot configure the connection between different cluster. 
4. I did go thru the **Detailed environment tuning recommendations docs**, and did everything in there excluding **Improving Performance in Shuffle Handler and IFile Reader
** and **Best Practices for MapReduce Configuration
** since we don't have any Hadoop binaries yet.

**Comment by Dzndrx** [comment]
# MySQL/MariaDB Installation Lab

> I did use mariadb since Im using Centos 7.4.1408 (Core)

1. As agreed, we install a single instance of mariadb and can do the replication later.
2. Also, MariaDB is installed on a the Cloudera Manager node.
3. Modify the /etc/my.cnf for cloudera recommended settings.
3. Created a database named 'scm' and a user 'scm' granted with all security privileges.

**Comment by Dzndrx** [comment]
# Cloudera Manager Install Lab

1. Using the cloudera-director.repo. We are able to install the JDK1.8.

> An important note here, we did configure the Environment variables in order to successfully complete the JDK1.8 installation because surprisingly it didn't configure/create the environment path when we install JDK 1.8. 

2. Downloaded JDBC connector from MySql website and mv the bin/jar file to /usr/share/java/mysql-connector-java.jar 

> JDBC Connecter is installed on all nodes

3. Using the cloudera-manager.repo. to install cloudera-manager-server.x86_64 and use the /usr/share/cmf/schema/scm_prepare_database.sh in order to establish the tables for different component. 
4. Start the cloudera-scm-server

**Comment by Dzndrx** [comment]
# Hive Metastore won't start

Hi @manojsundaram  Im stuck in this hive metastore problem, it seems that there are no created metastore table for the hive. Here is a piece of error from the log. I can keep going on debugging this but It already consume so much time and I decided to ask for your help. 

I already face this issue in MapR and what I did is update the version of hive schema metastore and run the schematool to create the tables. 

I already did the same thing but no luck. Also I did the use the Cloudera manager UI to create the metastore table and It is successful but when I tried to restart the hive metstore it still output this error. Hope you can reply on this, I really want to finish this one so I can continue to the HDFS stuff.

`2018-05-15 09:55:30,887 INFO  org.apache.hadoop.hive.metastore.HiveMetaStore: [main]: Starting hive metastore on port 9083
2018-05-15 09:55:31,573 INFO  org.apache.hadoop.hive.metastore.HiveMetaStore: [main]: 0: Opening raw store with implemenation class:org.apache.hadoop.hive.metastore.ObjectStore
2018-05-15 09:55:31,955 INFO  org.apache.hadoop.hive.metastore.ObjectStore: [main]: ObjectStore, initialize called
2018-05-15 09:55:32,327 INFO  DataNucleus.Persistence: [main]: Property hive.metastore.integral.jdo.pushdown unknown - will be ignored
2018-05-15 09:55:32,327 INFO  DataNucleus.Persistence: [main]: Property datanucleus.cache.level2 unknown - will be ignored
2018-05-15 09:55:33,406 INFO  org.apache.hadoop.hive.metastore.ObjectStore: [main]: Setting MetaStore object pin classes with hive.metastore.cache.pinobjtypes="Table,StorageDescriptor,SerDeInfo,Partition,Database,Type,FieldSchema,Order"
2018-05-15 09:55:34,520 WARN  DataNucleus.Query: [main]: Query for candidates of org.apache.hadoop.hive.metastore.model.MDatabase and subclasses resulted in no possible candidates
Required table missing : "`DBS`" in Catalog "" Schema "". DataNucleus requires this table to perform its persistence operations. Either your MetaData is incorrect, or you need to enable "datanucleus.autoCreateTables"
org.datanucleus.store.rdbms.exceptions.MissingTableException: Required table missing : "`DBS`" in Catalog "" Schema "". DataNucleus requires this table to perform its persistence operations. Either your MetaData is incorrect, or you need to enable "datanucleus.autoCreateTables"
	at org.datanucleus.store.rdbms.table.AbstractTable.exists(AbstractTable.java:485)
	at org.datanucleus.store.rdbms.RDBMSStoreManager$ClassAdder.performTablesValidation(RDBMSStoreManager.java:3380)
	at org.datanucleus.store.rdbms.RDBMSStoreManager$ClassAdder.addClassTablesAndValidate(RDBMSStoreManager.java:3190)
	at org.datanucleus.store.rdbms.RDBMSStoreManager$ClassAdder.run(RDBMSStoreManager.java:2841)
	at org.datanucleus.store.rdbms.AbstractSchemaTransaction.execute(AbstractSchemaTransaction.java:122)
	at org.datanucleus.store.rdbms.RDBMSStoreManager.addClasses(RDBMSStoreManager.java:1605)
	at org.datanucleus.store.AbstractStoreManager.addClass(AbstractStoreManager.java:954)
	at org.datanucleus.store.rdbms.RDBMSStoreManager.getDatastoreClass(RDBMSStoreManager.java:679)
	at org.datanucleus.store.rdbms.query.RDBMSQueryUtils.getStatementForCandidates(RDBMSQueryUtils.java:408)
	at org.datanucleus.store.rdbms.query.JDOQLQuery.compileQueryFull(JDOQLQuery.java:947)
	at org.datanucleus.store.rdbms.query.JDOQLQuery.compileInternal(JDOQLQuery.java:370)
	at org.datanucleus.store.query.Query.executeQuery(Query.java:1744)
	at org.datanucleus.store.query.Query.executeWithArray(Query.java:1672)
	at org.datanucleus.store.query.Query.execute(Query.java:1654)
	at org.datanucleus.api.jdo.JDOQuery.execute(JDOQuery.java:221)
	at org.apache.hadoop.hive.metastore.MetaStoreDirectSql.ensureDbInit(MetaStoreDirectSql.java:183)
	at org.apache.hadoop.hive.metastore.MetaStoreDirectSql.<init>(MetaStoreDirectSql.java:134)
	at org.apache.hadoop.hive.metastore.ObjectStore.initialize(ObjectStore.java:347)
	at org.apache.hadoop.hive.metastore.ObjectStore.setConf(ObjectStore.java:298)
	at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:73)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:133)
	at org.apache.hadoop.hive.metastore.RawStoreProxy.<init>(RawStoreProxy.java:60)
	at org.apache.hadoop.hive.metastore.RawStoreProxy.getProxy(RawStoreProxy.java:69)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.newRawStore(HiveMetaStore.java:682)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.getMS(HiveMetaStore.java:660)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.createDefaultDB(HiveMetaStore.java:709)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.init(HiveMetaStore.java:508)
	at org.apache.hadoop.hive.metastore.RetryingHMSHandler.<init>(RetryingHMSHandler.java:78)
	at org.apache.hadoop.hive.metastore.RetryingHMSHandler.getProxy(RetryingHMSHandler.java:84)
	at org.apache.hadoop.hive.metastore.HiveMetaStore.newRetryingHMSHandler(HiveMetaStore.java:6475)
	at org.apache.hadoop.hive.metastore.HiveMetaStore.newRetryingHMSHandler(HiveMetaStore.java:6470)
	at org.apache.hadoop.hive.metastore.HiveMetaStore.startMetaStore(HiveMetaStore.java:6720)
	at org.apache.hadoop.hive.metastore.HiveMetaStore.main(HiveMetaStore.java:6647)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
2018-05-15 09:55:34,524 INFO  DataNucleus.Datastore: [main]: The class "org.apache.hadoop.hive.metastore.model.MFieldSchema" is tagged as "embedded-only" so does not have its own datastore table.
2018-05-15 09:55:34,524 INFO  DataNucleus.Datastore: [main]: The class "org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
2018-05-15 09:55:34,549 WARN  DataNucleus.Query: [main]: Query for candidates of org.apache.hadoop.hive.metastore.model.MTableColumnStatistics and subclasses resulted in no possible candidates
Required table missing : "`SKEWED_STRING_LIST`" in Catalog "" Schema "". DataNucleus requires this table to perform its persistence operations. Either your MetaData is incorrect, or you need to enable "datanucleus.autoCreateTables"
org.datanucleus.store.rdbms.exceptions.MissingTableException: Required table missing : "`SKEWED_STRING_LIST`" in Catalog "" Schema "". DataNucleus requires this table to perform its persistence operations. Either your MetaData is incorrect, or you need to enable "datanucleus.autoCreateTables"`

**Comment by Dzndrx** [comment]
#Hive Metastore successfully started


**Problem**

Hive, Hue, and Oozie resides on a single database.

**Resolution**

Created a seperate database for Hive, Hue, Ooozie and recreate the table using cloudera manager.
